library(readr)
datacapstonefinal <- read_csv("~/Desktop/datacapstonefinal.csv")
View(datacapstonefinal)
library(psych)
df1 <- data.frame(LCO2 = datacapstonefinal$LCO2, LGDP = datacapstonefinal$LGDP,LURBAN = datacapstonefinal$LURBAN)
library(psych)
describe(df1)
library(plm)
cap.panel <- pdata.frame(datacapstonefinal, index = c("Country", "Year"))
cap.panel <- make.pbalanced(cap.panel, "shared.individuals")
pdim(cap.panel)
library(dplyr)
cap.panel$co2 <- cap.panel$`Per capita CO₂ emissions (tonnes per capita)`
cap.panel$LCO2 <- log(cap.panel$co2 + 1)
#whole model 
whole_pols <- plm(LCO2~LGDP + LGDP_2 + LGDP_3 + LURBAN  , effect = "twoway", model = "pooling", data = cap.panel)
summary(whole_pols)
whole_fe <- plm(LCO2~LGDP + LGDP_2 + LGDP_3 + LURBAN, effect = "twoway", model = "within", data = cap.panel)
summary(whole_fe)
whole_re <- plm(LCO2~LGDP + LGDP_2 + LGDP_3 + LURBAN  , effect = "twoway", model = "random", data = cap.panel)
summary(whole_re)
stargazer(whole_fe,whole_pols, whole_re, type = "text", column.labels = c("FEM", "POLS", "REM"), title = "FEM, POLS vs REM for the whole sample")
pFtest(whole_fe,whole_pols)
phtest(whole_fe,whole_re)
AB_GMM11 <- pgmm(LCO2 ~ lag(LCO2) + LGDP + LGDP_2 + LGDP_3 + LURBAN  | lag(LCO2, 2:99) , data = cap.panel, effect = "twoways", model = "onestep")
summary(AB_GMM11, time.dummies=FALSE)
stargazer(whole_fe,AB_GMM11, label =c("FEM", "GMM"),type="text",title="FEM vs GMM Model")
sargan(AB_GMM11)
#highincome
datacapstonefinal$co2 <- datacapstonefinal$`Per capita CO₂ emissions (tonnes per capita)`
datacapstonefinal$LCO2 <- log(datacapstonefinal$co2 + 1)
highincome <- datacapstonefinal %>%filter(IncomeGroup == "High income")
highincome <- pdata.frame(highincome, index = c("Country", "Year"))
highincome<- make.pbalanced(highincome, "shared.individuals")
high_fe <- plm(LCO2~LGDP + LGDP_2 + LGDP_3 + LURBAN  , effect = "twoway", model = "within", data = highincome)
summary(high_fe)
high_pols <- plm(LCO2~LGDP + LGDP_2 + LGDP_3 + LURBAN  , effect = "twoway", model = "pooling", data = highincome)
summary(high_pols)
AB_GMM2 <- pgmm(LCO2 ~ lag(LCO2) + LGDP+LGDP_2+LGDP_3+ LURBAN| lag(LCO2, 2:99) , data = highincome, effect = "twoways", model = "onestep")
summary(AB_GMM2, time.dummies=FALSE)
#lowincome
lowincome <- datacapstonefinal %>%filter(IncomeGroup == "Low income")
lowincome.panel <- pdata.frame(lowincome, index = c("Country", "Year"))
lowincome.panel<- make.pbalanced(lowincome.panel, "shared.individuals")
low_fe <- plm(LCO2~LGDP + LGDP_2 + LGDP_3 + LURBAN, effect = "twoway", model = "within", data = lowincome.panel)
summary(low_fe)
low_pooling <- plm(LCO2~LGDP + LGDP_2 + LGDP_3 + LURBAN, effect = "twoway", model = "pooling", data = lowincome.panel)
summary(low_pooling)
#upper middle
uppermiddleincome <- datacapstonefinal %>%filter(IncomeGroup == "Upper middle income")
uppermiddle.panel <- pdata.frame(uppermiddleincome, index = c("Country", "Year"))
uppermiddleincome.panel<- make.pbalanced(uppermiddle.panel, "shared.individuals")
uppermiddle_fe <- plm(LCO2~LGDP + LGDP_2 + LGDP_3 + LURBAN, effect = "twoway", model = "within", data = uppermiddleincome.panel)
summary(uppermiddle_fe)
uppermiddle_pols <- plm(LCO2~LGDP + LGDP_2 + LGDP_3 + LURBAN, effect = "twoway", model = "pooling", data = uppermiddleincome.panel)
summary(uppermiddle_pols)
AB_GMM4 <- pgmm(LCO2 ~ lag(LCO2) + LGDP+LGDP_2+LGDP_3+ LURBAN| lag(LCO2, 2:99) , data = uppermiddle.panel, effect = "twoways", model = "onestep")
lowermiddleincome <- datacapstonefinal %>%filter(IncomeGroup == "Lower middle income")
lowermiddle.panel <- pdata.frame(lowermiddleincome, index = c("Country", "Year"))
lowermiddle.panel<- make.pbalanced(lowermiddle.panel, "shared.individuals")
lowermiddle_fe <- plm(LCO2~LGDP + LGDP_2 + LGDP_3 + LURBAN , effect = "twoway", model = "within", data = lowermiddle.panel)
summary(lowermiddle_fe)
lowermiddle_pols <- plm(LCO2~LGDP + LGDP_2 + LGDP_3 + LURBAN , effect = "twoway", model = "pooling", data = lowermiddle.panel)
summary(lowermiddle_pols)
AB_GMM5 <- pgmm(LCO2 ~ lag(LCO2) + LGDP+LGDP_2+LGDP_3+ LURBAN| lag(LCO2, 2:99) , data = lowermiddle.panel, effect = "twoways", model = "onestep")
stargazer(whole_fe,high_fe,low_fe,uppermiddle_fe,lowermiddle_fe, type = "text", column.labels = c("Whole Sample", "High Income", "Low Income", "Upper Middle Income", "Lower Middle Income"), title = "FEM for Different Income Groups")

stargazer(AB_GMM11,AB_GMM2,AB_GMM4,AB_GMM5, type = "text", column.labels = c("Whole Sample", "High Income", "Upper Middle Income", "Lower Middle Income"), title = "GMM for Different Income Groups", omit.table.layout = "sn")